### ISSUE TITLE
Compilation error: kotlinext.js.JsObject seems to be missing in 1.3.72 libraries

### ISSUE THREAD

**Issue by night-crawler** [cfnz/muirwik#27]
After updating kotlin from 1.3.62 to 1.3.72 I've got a compilation error (and some other weird stuff).

Anyways, it seems that at least `toolbarJsCssToPartialCss` is using JsObject that has disappeared from the package.

**Comment by cfnz** [comment]
Got a new build coming soon... they just renamed JsObject to Object

**Comment by cfnz** [comment]
Hopefully the latest version closes this issue and doesn't raise any new ones.
New build type seems the way of the future, so have tried to embrace it.
